/**
 * Rosetta
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Amount from './Amount';
import BlockIdentifier from './BlockIdentifier';

/**
 * The AccountBalanceResponse model module.
 * @module model/AccountBalanceResponse
 * @version 1.3.1
 */
class AccountBalanceResponse {
    /**
     * Constructs a new <code>AccountBalanceResponse</code>.
     * An AccountBalanceResponse is returned on the /account/balance endpoint. If an account has a balance for each AccountIdentifier describing it (ex: an ERC-20 token balance on a few smart contracts), an account balance request must be made with each AccountIdentifier.
     * @alias module:model/AccountBalanceResponse
     * @param blockIdentifier {module:model/BlockIdentifier} 
     * @param balances {Array.<module:model/Amount>} A single account may have a balance in multiple currencies.
     */
    constructor(blockIdentifier, balances) { 
        
        AccountBalanceResponse.initialize(this, blockIdentifier, balances);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, blockIdentifier, balances) { 
        obj['block_identifier'] = blockIdentifier;
        obj['balances'] = balances;
    }

    /**
     * Constructs a <code>AccountBalanceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountBalanceResponse} obj Optional instance to populate.
     * @return {module:model/AccountBalanceResponse} The populated <code>AccountBalanceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountBalanceResponse();

            if (data.hasOwnProperty('block_identifier')) {
                obj['block_identifier'] = BlockIdentifier.constructFromObject(data['block_identifier']);
            }
            if (data.hasOwnProperty('balances')) {
                obj['balances'] = ApiClient.convertToType(data['balances'], [Amount]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BlockIdentifier} block_identifier
 */
AccountBalanceResponse.prototype['block_identifier'] = undefined;

/**
 * A single account may have a balance in multiple currencies.
 * @member {Array.<module:model/Amount>} balances
 */
AccountBalanceResponse.prototype['balances'] = undefined;

/**
 * Account-based blockchains that utilize a nonce or sequence number should include that number in the metadata. This number could be unique to the identifier or global across the account address.
 * @member {Object} metadata
 */
AccountBalanceResponse.prototype['metadata'] = undefined;






export default AccountBalanceResponse;

