/**
 * Rosetta
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Transaction from './Transaction';

/**
 * The BlockTransactionResponse model module.
 * @module model/BlockTransactionResponse
 * @version 1.3.1
 */
class BlockTransactionResponse {
    /**
     * Constructs a new <code>BlockTransactionResponse</code>.
     * A BlockTransactionResponse contains information about a block transaction.
     * @alias module:model/BlockTransactionResponse
     * @param transaction {module:model/Transaction} 
     */
    constructor(transaction) { 
        
        BlockTransactionResponse.initialize(this, transaction);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transaction) { 
        obj['transaction'] = transaction;
    }

    /**
     * Constructs a <code>BlockTransactionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockTransactionResponse} obj Optional instance to populate.
     * @return {module:model/BlockTransactionResponse} The populated <code>BlockTransactionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockTransactionResponse();

            if (data.hasOwnProperty('transaction')) {
                obj['transaction'] = Transaction.constructFromObject(data['transaction']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Transaction} transaction
 */
BlockTransactionResponse.prototype['transaction'] = undefined;






export default BlockTransactionResponse;

