/**
 * Rosetta
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetworkIdentifier from './NetworkIdentifier';

/**
 * The ConstructionSubmitRequest model module.
 * @module model/ConstructionSubmitRequest
 * @version 1.3.1
 */
class ConstructionSubmitRequest {
    /**
     * Constructs a new <code>ConstructionSubmitRequest</code>.
     * The transaction submission request includes a signed transaction.
     * @alias module:model/ConstructionSubmitRequest
     * @param networkIdentifier {module:model/NetworkIdentifier} 
     * @param signedTransaction {String} 
     */
    constructor(networkIdentifier, signedTransaction) { 
        
        ConstructionSubmitRequest.initialize(this, networkIdentifier, signedTransaction);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, networkIdentifier, signedTransaction) { 
        obj['network_identifier'] = networkIdentifier;
        obj['signed_transaction'] = signedTransaction;
    }

    /**
     * Constructs a <code>ConstructionSubmitRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConstructionSubmitRequest} obj Optional instance to populate.
     * @return {module:model/ConstructionSubmitRequest} The populated <code>ConstructionSubmitRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConstructionSubmitRequest();

            if (data.hasOwnProperty('network_identifier')) {
                obj['network_identifier'] = NetworkIdentifier.constructFromObject(data['network_identifier']);
            }
            if (data.hasOwnProperty('signed_transaction')) {
                obj['signed_transaction'] = ApiClient.convertToType(data['signed_transaction'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/NetworkIdentifier} network_identifier
 */
ConstructionSubmitRequest.prototype['network_identifier'] = undefined;

/**
 * @member {String} signed_transaction
 */
ConstructionSubmitRequest.prototype['signed_transaction'] = undefined;






export default ConstructionSubmitRequest;

