/**
 * Rosetta
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransactionIdentifier from './TransactionIdentifier';

/**
 * The MempoolResponse model module.
 * @module model/MempoolResponse
 * @version 1.3.1
 */
class MempoolResponse {
    /**
     * Constructs a new <code>MempoolResponse</code>.
     * A MempoolResponse contains all transaction identifiers in the mempool for a particular network_identifier.
     * @alias module:model/MempoolResponse
     * @param transactionIdentifiers {Array.<module:model/TransactionIdentifier>} 
     */
    constructor(transactionIdentifiers) { 
        
        MempoolResponse.initialize(this, transactionIdentifiers);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transactionIdentifiers) { 
        obj['transaction_identifiers'] = transactionIdentifiers;
    }

    /**
     * Constructs a <code>MempoolResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MempoolResponse} obj Optional instance to populate.
     * @return {module:model/MempoolResponse} The populated <code>MempoolResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MempoolResponse();

            if (data.hasOwnProperty('transaction_identifiers')) {
                obj['transaction_identifiers'] = ApiClient.convertToType(data['transaction_identifiers'], [TransactionIdentifier]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TransactionIdentifier>} transaction_identifiers
 */
MempoolResponse.prototype['transaction_identifiers'] = undefined;






export default MempoolResponse;

