/**
 * Copyright (c) 2020 DigiByte Foundation NZ Limited
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * Rosetta
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlockIdentifier from './BlockIdentifier';
import Peer from './Peer';

/**
 * The NetworkStatusResponse model module.
 * @module model/NetworkStatusResponse
 * @version 1.3.1
 */
class NetworkStatusResponse {
    /**
     * Constructs a new <code>NetworkStatusResponse</code>.
     * NetworkStatusResponse contains basic information about the node&#39;s view of a blockchain network.
     * @alias module:model/NetworkStatusResponse
     * @param currentBlockIdentifier {module:model/BlockIdentifier} 
     * @param currentBlockTimestamp {Number} The timestamp of the block in milliseconds since the Unix Epoch. The timestamp is stored in milliseconds because some blockchains produce blocks more often than once a second.
     * @param genesisBlockIdentifier {module:model/BlockIdentifier} 
     * @param peers {Array.<module:model/Peer>} 
     */
    constructor(currentBlockIdentifier, currentBlockTimestamp, genesisBlockIdentifier, peers) { 
        
        NetworkStatusResponse.initialize(this, currentBlockIdentifier, currentBlockTimestamp, genesisBlockIdentifier, peers);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currentBlockIdentifier, currentBlockTimestamp, genesisBlockIdentifier, peers) { 
        obj['current_block_identifier'] = currentBlockIdentifier;
        obj['current_block_timestamp'] = currentBlockTimestamp;
        obj['genesis_block_identifier'] = genesisBlockIdentifier;
        obj['peers'] = peers;
    }

    /**
     * Constructs a <code>NetworkStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NetworkStatusResponse} obj Optional instance to populate.
     * @return {module:model/NetworkStatusResponse} The populated <code>NetworkStatusResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkStatusResponse();

            if (data.hasOwnProperty('current_block_identifier')) {
                obj['current_block_identifier'] = BlockIdentifier.constructFromObject(data['current_block_identifier']);
            }
            if (data.hasOwnProperty('current_block_timestamp')) {
                obj['current_block_timestamp'] = ApiClient.convertToType(data['current_block_timestamp'], 'Number');
            }
            if (data.hasOwnProperty('genesis_block_identifier')) {
                obj['genesis_block_identifier'] = BlockIdentifier.constructFromObject(data['genesis_block_identifier']);
            }
            if (data.hasOwnProperty('peers')) {
                obj['peers'] = ApiClient.convertToType(data['peers'], [Peer]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BlockIdentifier} current_block_identifier
 */
NetworkStatusResponse.prototype['current_block_identifier'] = undefined;

/**
 * The timestamp of the block in milliseconds since the Unix Epoch. The timestamp is stored in milliseconds because some blockchains produce blocks more often than once a second.
 * @member {Number} current_block_timestamp
 */
NetworkStatusResponse.prototype['current_block_timestamp'] = undefined;

/**
 * @member {module:model/BlockIdentifier} genesis_block_identifier
 */
NetworkStatusResponse.prototype['genesis_block_identifier'] = undefined;

/**
 * @member {Array.<module:model/Peer>} peers
 */
NetworkStatusResponse.prototype['peers'] = undefined;






export default NetworkStatusResponse;

