/**
 * Copyright (c) 2020 DigiByte Foundation NZ Limited
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * Rosetta
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetworkIdentifier from './NetworkIdentifier';

/**
 * The NetworkListResponse model module.
 * @module model/NetworkListResponse
 * @version 1.3.1
 */
class NetworkListResponse {
    /**
     * Constructs a new <code>NetworkListResponse</code>.
     * A NetworkListResponse contains all NetworkIdentifiers that the node can serve information for.
     * @alias module:model/NetworkListResponse
     * @param networkIdentifiers {Array.<module:model/NetworkIdentifier>} 
     */
    constructor(networkIdentifiers) { 
        
        NetworkListResponse.initialize(this, networkIdentifiers);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, networkIdentifiers) { 
        obj['network_identifiers'] = networkIdentifiers;
    }

    /**
     * Constructs a <code>NetworkListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NetworkListResponse} obj Optional instance to populate.
     * @return {module:model/NetworkListResponse} The populated <code>NetworkListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkListResponse();

            if (data.hasOwnProperty('network_identifiers')) {
                obj['network_identifiers'] = ApiClient.convertToType(data['network_identifiers'], [NetworkIdentifier]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/NetworkIdentifier>} network_identifiers
 */
NetworkListResponse.prototype['network_identifiers'] = undefined;






export default NetworkListResponse;

